import rawCountries from '@/data/countries.json';
import type { ComboboxOption } from '@/components/Combobox.vue';

export interface CountryData {
    code: string;
    name: string;
    flag: string;
    currency: string;
    timezone: string;
    locale: string;
}

export const COUNTRIES_DATA: CountryData[] = rawCountries as CountryData[];

export const COUNTRY_OPTIONS: ComboboxOption[] = COUNTRIES_DATA.map((c) => ({
    label: `${c.name} (${c.code})`,
    value: c.code,
    flag: c.flag,
}));

export const CURRENCY_OPTIONS: ComboboxOption[] = [
    { label: 'USD - US Dollar ($)', value: 'USD', flag: '🇺🇸' },
    { label: 'EUR - Euro (€)', value: 'EUR', flag: '🇪🇺' },
    { label: 'GBP - British Pound (£)', value: 'GBP', flag: '🇬🇧' },
    { label: 'NPR - Nepalese Rupee (Rs)', value: 'NPR', flag: '🇳🇵' },
    { label: 'INR - Indian Rupee (₹)', value: 'INR', flag: '🇮🇳' },
    { label: 'MYR - Malaysian Ringgit (RM)', value: 'MYR', flag: '🇲🇾' },
    { label: 'SGD - Singapore Dollar (S$)', value: 'SGD', flag: '🇸🇬' },
    { label: 'AED - UAE Dirham (د.إ)', value: 'AED', flag: '🇦🇪' },
    { label: 'SAR - Saudi Riyal (﷼)', value: 'SAR', flag: '🇸🇦' },
    { label: 'QAR - Qatari Riyal (﷼)', value: 'QAR', flag: '🇶🇦' },
    { label: 'AUD - Australian Dollar (A$)', value: 'AUD', flag: '🇦🇺' },
    { label: 'CAD - Canadian Dollar (C$)', value: 'CAD', flag: '🇨🇦' },
    { label: 'JPY - Japanese Yen (¥)', value: 'JPY', flag: '🇯🇵' },
    { label: 'CNY - Chinese Yuan (¥)', value: 'CNY', flag: '🇨🇳' },
    { label: 'HKD - Hong Kong Dollar (HK$)', value: 'HKD', flag: '🇭🇰' },
    { label: 'CHF - Swiss Franc (CHF)', value: 'CHF', flag: '🇨🇭' },
    { label: 'IDR - Indonesian Rupiah (Rp)', value: 'IDR', flag: '🇮🇩' },
    { label: 'THB - Thai Baht (฿)', value: 'THB', flag: '🇹🇭' },
    { label: 'PHP - Philippine Peso (₱)', value: 'PHP', flag: '🇵🇭' },
    { label: 'VND - Vietnamese Dong (₫)', value: 'VND', flag: '🇻🇳' },
    { label: 'KRW - South Korean Won (₩)', value: 'KRW', flag: '🇰🇷' },
    { label: 'NZD - New Zealand Dollar (NZ$)', value: 'NZD', flag: '🇳🇿' },
    { label: 'ZAR - South African Rand (R)', value: 'ZAR', flag: '🇿🇦' },
    { label: 'BRL - Brazilian Real (R$)', value: 'BRL', flag: '🇧🇷' },
    { label: 'MXN - Mexican Peso (Mex$)', value: 'MXN', flag: '🇲🇽' },
    { label: 'TRY - Turkish Lira (₺)', value: 'TRY', flag: '🇹🇷' },
    { label: 'SEK - Swedish Krona (kr)', value: 'SEK', flag: '🇸🇪' },
    { label: 'NOK - Norwegian Krone (kr)', value: 'NOK', flag: '🇳🇴' },
    { label: 'DKK - Danish Krone (kr)', value: 'DKK', flag: '🇩🇰' },
    { label: 'PLN - Polish Zloty (zł)', value: 'PLN', flag: '🇵🇱' },
    { label: 'BDT - Bangladeshi Taka (৳)', value: 'BDT', flag: '🇧🇩' },
    { label: 'PKR - Pakistani Rupee (Rs)', value: 'PKR', flag: '🇵🇰' },
    { label: 'LKR - Sri Lankan Rupee (Rs)', value: 'LKR', flag: '🇱🇰' },
    { label: 'AFN - Afghan Afghani (؋)', value: 'AFN', flag: '🇦🇫' },
    { label: 'ALL - Albanian Lek (L)', value: 'ALL', flag: '🇦🇱' },
    { label: 'AMD - Armenian Dram (֏)', value: 'AMD', flag: '🇦🇲' },
    { label: 'AOA - Angolan Kwanza (Kz)', value: 'AOA', flag: '🇦🇴' },
    { label: 'ARS - Argentine Peso ($)', value: 'ARS', flag: '🇦🇷' },
    { label: 'AZN - Azerbaijani Manat (₼)', value: 'AZN', flag: '🇦🇿' },
    { label: 'BAM - Bosnia-Herzegovina Mark (KM)', value: 'BAM', flag: '🇧🇦' },
    { label: 'BBD - Barbadian Dollar ($)', value: 'BBD', flag: '🇧🇧' },
    { label: 'BGN - Bulgarian Lev (лв)', value: 'BGN', flag: '🇧🇬' },
    { label: 'BHD - Bahraini Dinar (.د.ب)', value: 'BHD', flag: '🇧🇭' },
    { label: 'BIF - Burundian Franc (FBu)', value: 'BIF', flag: '🇧🇮' },
    { label: 'BND - Brunei Dollar ($)', value: 'BND', flag: '🇧🇳' },
    { label: 'BOB - Bolivian Boliviano (Bs.)', value: 'BOB', flag: '🇧🇴' },
    { label: 'BSD - Bahamian Dollar ($)', value: 'BSD', flag: '🇧🇸' },
    { label: 'BTN - Bhutanese Ngultrum (Nu.)', value: 'BTN', flag: '🇧🇹' },
    { label: 'BWP - Botswanan Pula (P)', value: 'BWP', flag: '🇧🇼' },
    { label: 'BYN - Belarusian Ruble (Br)', value: 'BYN', flag: '🇧🇾' },
    { label: 'BZD - Belize Dollar ($)', value: 'BZD', flag: '🇧🇿' },
    { label: 'CDF - Congolese Franc (FC)', value: 'CDF', flag: '🇨🇩' },
    { label: 'CLP - Chilean Peso ($)', value: 'CLP', flag: '🇨🇱' },
    { label: 'COP - Colombian Peso ($)', value: 'COP', flag: '🇨🇴' },
    { label: 'CRC - Costa Rican Colón (₡)', value: 'CRC', flag: '🇨🇷' },
    { label: 'CUP - Cuban Peso ($)', value: 'CUP', flag: '🇨🇺' },
    { label: 'CVE - Cape Verdean Escudo ($)', value: 'CVE', flag: '🇨🇻' },
    { label: 'CZK - Czech Koruna (Kč)', value: 'CZK', flag: '🇨🇿' },
    { label: 'DJF - Djiboutian Franc (Fdj)', value: 'DJF', flag: '🇩🇯' },
    { label: 'DOP - Dominican Peso ($)', value: 'DOP', flag: '🇩🇴' },
    { label: 'DZD - Algerian Dinar (دج)', value: 'DZD', flag: '🇩🇿' },
    { label: 'EGP - Egyptian Pound (E£)', value: 'EGP', flag: '🇪🇬' },
    { label: 'ERN - Eritrean Nakfa (Nfk)', value: 'ERN', flag: '🇪🇷' },
    { label: 'ETB - Ethiopian Birr (Br)', value: 'ETB', flag: '🇪🇹' },
    { label: 'FJD - Fijian Dollar ($)', value: 'FJD', flag: '🇫🇯' },
    { label: 'GEL - Georgian Lari (₾)', value: 'GEL', flag: '🇬🇪' },
    { label: 'GHS - Ghanaian Cedi (₵)', value: 'GHS', flag: '🇬🇭' },
    { label: 'GMD - Gambian Dalasi (D)', value: 'GMD', flag: '🇬🇲' },
    { label: 'GNF - Guinean Franc (FG)', value: 'GNF', flag: '🇬🇳' },
    { label: 'GTQ - Guatemalan Quetzal (Q)', value: 'GTQ', flag: '🇬🇹' },
    { label: 'GYD - Guyanaese Dollar ($)', value: 'GYD', flag: '🇬🇾' },
    { label: 'HNL - Honduran Lempira (L)', value: 'HNL', flag: '🇭🇳' },
    { label: 'HRK - Croatian Kuna (kn)', value: 'HRK', flag: '🇭🇷' },
    { label: 'HTG - Haitian Gourde (G)', value: 'HTG', flag: '🇭🇹' },
    { label: 'HUF - Hungarian Forint (Ft)', value: 'HUF', flag: '🇭🇺' },
    { label: 'ILS - Israeli New Shekel (₪)', value: 'ILS', flag: '🇮🇱' },
    { label: 'IQD - Iraqi Dinar (ع.د)', value: 'IQD', flag: '🇮🇶' },
    { label: 'IRR - Iranian Rial (﷼)', value: 'IRR', flag: '🇮🇷' },
    { label: 'ISK - Icelandic Króna (kr)', value: 'ISK', flag: '🇮🇸' },
    { label: 'JMD - Jamaican Dollar ($)', value: 'JMD', flag: '🇯🇲' },
    { label: 'JOD - Jordanian Dinar (JD)', value: 'JOD', flag: '🇯🇴' },
    { label: 'KES - Kenyan Shilling (KSh)', value: 'KES', flag: '🇰🇪' },
    { label: 'KGS - Kyrgystani Som (с)', value: 'KGS', flag: '🇰🇬' },
    { label: 'KHR - Cambodian Riel (៛)', value: 'KHR', flag: '🇰🇭' },
    { label: 'KMF - Comorian Franc (CF)', value: 'KMF', flag: '🇰🇲' },
    { label: 'KWD - Kuwaiti Dinar (KD)', value: 'KWD', flag: '🇰🇼' },
    { label: 'KZT - Kazakhstani Tenge (₸)', value: 'KZT', flag: '🇰🇿' },
    { label: 'LAK - Laotian Kip (₭)', value: 'LAK', flag: '🇱🇦' },
    { label: 'LBP - Lebanese Pound (L£)', value: 'LBP', flag: '🇱🇧' },
    { label: 'LRD - Liberian Dollar ($)', value: 'LRD', flag: '🇱🇷' },
    { label: 'LSL - Lesotho Loti (L)', value: 'LSL', flag: '🇱🇸' },
    { label: 'LYD - Libyan Dinar (LD)', value: 'LYD', flag: '🇱🇾' },
    { label: 'MAD - Moroccan Dirham (MAD)', value: 'MAD', flag: '🇲🇦' },
    { label: 'MDL - Moldovan Leu (L)', value: 'MDL', flag: '🇲🇩' },
    { label: 'MGA - Malagasy Ariary (Ar)', value: 'MGA', flag: '🇲🇬' },
    { label: 'MKD - Macedonian Denar (ден)', value: 'MKD', flag: '🇲🇰' },
    { label: 'MMK - Myanmar Kyat (K)', value: 'MMK', flag: '🇲🇲' },
    { label: 'MNT - Mongolian Tugrik (₮)', value: 'MNT', flag: '🇲🇳' },
    { label: 'MOP - Macanese Pataca (MOP$)', value: 'MOP', flag: '🇲🇴' },
    { label: 'MRU - Mauritanian Ouguiya (UM)', value: 'MRU', flag: '🇲🇷' },
    { label: 'MUR - Mauritian Rupee (₨)', value: 'MUR', flag: '🇲🇺' },
    { label: 'MVR - Maldivian Rufiyaa (Rf)', value: 'MVR', flag: '🇲🇻' },
    { label: 'MWK - Malawian Kwacha (MK)', value: 'MWK', flag: '🇲🇼' },
    { label: 'MZN - Mozambican Metical (MT)', value: 'MZN', flag: '🇲🇿' },
    { label: 'NAD - Namibian Dollar ($)', value: 'NAD', flag: '🇳🇦' },
    { label: 'NGN - Nigerian Naira (₦)', value: 'NGN', flag: '🇳🇬' },
    { label: 'NIO - Nicaraguan Córdoba (C$)', value: 'NIO', flag: '🇳🇮' },
    { label: 'OMR - Omani Rial (﷼)', value: 'OMR', flag: '🇴🇲' },
    { label: 'PAB - Panamanian Balboa (B/.)', value: 'PAB', flag: '🇵🇦' },
    { label: 'PEN - Peruvian Sol (S/.)', value: 'PEN', flag: '🇵🇪' },
    { label: 'PGK - Papua New Guinean Kina (K)', value: 'PGK', flag: '🇵🇬' },
    { label: 'RSD - Serbian Dinar (дин.)', value: 'RSD', flag: '🇷🇸' },
    { label: 'RUB - Russian Ruble (₽)', value: 'RUB', flag: '🇷🇺' },
    { label: 'RWF - Rwandan Franc (FRw)', value: 'RWF', flag: '🇷🇼' },
    { label: 'SBD - Solomon Islands Dollar ($)', value: 'SBD', flag: '🇸🇧' },
    { label: 'SCR - Seychellois Rupee (₨)', value: 'SCR', flag: '🇸🇨' },
    { label: 'SDG - Sudanese Pound (SDG)', value: 'SDG', flag: '🇸🇩' },
    { label: 'SOS - Somali Shilling (S)', value: 'SOS', flag: '🇸🇴' },
    { label: 'SRD - Surinamese Dollar ($)', value: 'SRD', flag: '🇸🇷' },
    { label: 'SZL - Swazi Lilangeni (L)', value: 'SZL', flag: '🇸🇿' },
    { label: 'TJS - Tajikistani Somoni (ЅМ)', value: 'TJS', flag: '🇹🇯' },
    { label: 'TMT - Turkmenistani Manat (T)', value: 'TMT', flag: '🇹🇲' },
    { label: 'TND - Tunisian Dinar (DT)', value: 'TND', flag: '🇹🇳' },
    { label: 'TOP - Tongan Paʻanga (T$)', value: 'TOP', flag: '🇹🇴' },
    { label: 'TTD - Trinidad & Tobago Dollar ($)', value: 'TTD', flag: '🇹🇹' },
    { label: 'TWD - New Taiwan Dollar (NT$)', value: 'TWD', flag: '🇹🇼' },
    { label: 'TZS - Tanzanian Shilling (TSh)', value: 'TZS', flag: '🇹🇿' },
    { label: 'UAH - Ukrainian Hryvnia (₴)', value: 'UAH', flag: '🇺🇦' },
    { label: 'UGX - Ugandan Shilling (USh)', value: 'UGX', flag: '🇺🇬' },
    { label: 'UYU - Uruguayan Peso ($U)', value: 'UYU', flag: '🇺🇾' },
    { label: 'UZS - Uzbekistani Som (soʻm)', value: 'UZS', flag: '🇺🇿' },
    { label: 'VES - Venezuelan Bolívar (Bs.S)', value: 'VES', flag: '🇻🇪' },
    { label: 'VUV - Vanuatu Vatu (VT)', value: 'VUV', flag: '🇻🇺' },
    { label: 'WST - Samoan Tala (WS$)', value: 'WST', flag: '🇼🇸' },
    { label: 'XAF - Central African CFA Franc (FCFA)', value: 'XAF', flag: '🇨🇲' },
    { label: 'XCD - East Caribbean Dollar ($)', value: 'XCD', flag: '🇦🇬' },
    { label: 'XOF - West African CFA Franc (CFA)', value: 'XOF', flag: '🇸🇳' },
    { label: 'XPF - CFP Franc (₣)', value: 'XPF', flag: '🇵🇫' },
    { label: 'YER - Yemeni Rial (﷼)', value: 'YER', flag: '🇾🇪' },
    { label: 'ZMW - Zambian Kwacha (ZK)', value: 'ZMW', flag: '🇿🇲' },
    { label: 'ZWG - Zimbabwean Gold (ZiG)', value: 'ZWG', flag: '🇿🇼' },
];

export const TIMEZONE_OPTIONS: ComboboxOption[] = [
    { label: 'Asia/Kuala_Lumpur (UTC+08:00)', value: 'Asia/Kuala_Lumpur' },
    { label: 'Asia/Kathmandu (UTC+05:45)', value: 'Asia/Kathmandu' },
    { label: 'Asia/Singapore (UTC+08:00)', value: 'Asia/Singapore' },
    { label: 'Asia/Kolkata (UTC+05:30)', value: 'Asia/Kolkata' },
    { label: 'Asia/Dubai (UTC+04:00)', value: 'Asia/Dubai' },
    { label: 'Asia/Riyadh (UTC+03:00)', value: 'Asia/Riyadh' },
    { label: 'Asia/Bangkok (UTC+07:00)', value: 'Asia/Bangkok' },
    { label: 'Asia/Jakarta (UTC+07:00)', value: 'Asia/Jakarta' },
    { label: 'Asia/Tokyo (UTC+09:00)', value: 'Asia/Tokyo' },
    { label: 'Asia/Seoul (UTC+09:00)', value: 'Asia/Seoul' },
    { label: 'Asia/Hong_Kong (UTC+08:00)', value: 'Asia/Hong_Kong' },
    { label: 'Asia/Shanghai (UTC+08:00)', value: 'Asia/Shanghai' },
    { label: 'Asia/Dhaka (UTC+06:00)', value: 'Asia/Dhaka' },
    { label: 'Asia/Karachi (UTC+05:00)', value: 'Asia/Karachi' },
    { label: 'Asia/Colombo (UTC+05:30)', value: 'Asia/Colombo' },
    { label: 'UTC (UTC+00:00)', value: 'UTC' },
    { label: 'Europe/London (UTC+00:00)', value: 'Europe/London' },
    { label: 'Europe/Paris (UTC+01:00)', value: 'Europe/Paris' },
    { label: 'Europe/Berlin (UTC+01:00)', value: 'Europe/Berlin' },
    { label: 'Europe/Rome (UTC+01:00)', value: 'Europe/Rome' },
    { label: 'Europe/Madrid (UTC+01:00)', value: 'Europe/Madrid' },
    { label: 'Europe/Amsterdam (UTC+01:00)', value: 'Europe/Amsterdam' },
    { label: 'Europe/Zurich (UTC+01:00)', value: 'Europe/Zurich' },
    { label: 'Europe/Istanbul (UTC+03:00)', value: 'Europe/Istanbul' },
    { label: 'Europe/Athens (UTC+02:00)', value: 'Europe/Athens' },
    { label: 'Europe/Kyiv (UTC+02:00)', value: 'Europe/Kyiv' },
    { label: 'Europe/Moscow (UTC+03:00)', value: 'Europe/Moscow' },
    { label: 'America/New_York (UTC-05:00)', value: 'America/New_York' },
    { label: 'America/Chicago (UTC-06:00)', value: 'America/Chicago' },
    { label: 'America/Denver (UTC-07:00)', value: 'America/Denver' },
    { label: 'America/Los_Angeles (UTC-08:00)', value: 'America/Los_Angeles' },
    { label: 'America/Toronto (UTC-05:00)', value: 'America/Toronto' },
    { label: 'America/Vancouver (UTC-08:00)', value: 'America/Vancouver' },
    { label: 'America/Mexico_City (UTC-06:00)', value: 'America/Mexico_City' },
    { label: 'America/Sao_Paulo (UTC-03:00)', value: 'America/Sao_Paulo' },
    { label: 'America/Buenos_Aires (UTC-03:00)', value: 'America/Buenos_Aires' },
    { label: 'America/Bogota (UTC-05:00)', value: 'America/Bogota' },
    { label: 'Africa/Cairo (UTC+02:00)', value: 'Africa/Cairo' },
    { label: 'Africa/Johannesburg (UTC+02:00)', value: 'Africa/Johannesburg' },
    { label: 'Africa/Lagos (UTC+01:00)', value: 'Africa/Lagos' },
    { label: 'Africa/Nairobi (UTC+03:00)', value: 'Africa/Nairobi' },
    { label: 'Australia/Sydney (UTC+10:00)', value: 'Australia/Sydney' },
    { label: 'Australia/Melbourne (UTC+10:00)', value: 'Australia/Melbourne' },
    { label: 'Australia/Perth (UTC+08:00)', value: 'Australia/Perth' },
    { label: 'Pacific/Auckland (UTC+12:00)', value: 'Pacific/Auckland' },
    { label: 'Pacific/Honolulu (UTC-10:00)', value: 'Pacific/Honolulu' },
];

export const LOCALE_OPTIONS: ComboboxOption[] = [
    { label: 'English', value: 'en', flag: '🇺🇸' },
    { label: 'नेपाली (Nepali)', value: 'ne', flag: '🇳🇵' },
    { label: 'हिन्दी (Hindi)', value: 'hi', flag: '🇮🇳' },
    { label: 'Bahasa Melayu', value: 'ms', flag: '🇲🇾' },
    { label: 'العربية (Arabic)', value: 'ar', flag: '🇸🇦' },
    { label: 'Español (Spanish)', value: 'es', flag: '🇪🇸' },
    { label: 'Français (French)', value: 'fr', flag: '🇫🇷' },
    { label: 'Deutsch (German)', value: 'de', flag: '🇩🇪' },
    { label: '中文 (Chinese)', value: 'zh', flag: '🇨🇳' },
    { label: '日本語 (Japanese)', value: 'ja', flag: '🇯🇵' },
    { label: '한국어 (Korean)', value: 'ko', flag: '🇰🇷' },
    { label: 'Português (Portuguese)', value: 'pt', flag: '🇵🇹' },
    { label: 'Português do Brasil', value: 'pt-BR', flag: '🇧🇷' },
    { label: 'Русский (Russian)', value: 'ru', flag: '🇷🇺' },
    { label: 'Italiano (Italian)', value: 'it', flag: '🇮🇹' },
    { label: 'Nederlands (Dutch)', value: 'nl', flag: '🇳🇱' },
    { label: 'Türkçe (Turkish)', value: 'tr', flag: '🇹🇷' },
    { label: 'ไทย (Thai)', value: 'th', flag: '🇹🇭' },
    { label: 'Tiếng Việt (Vietnamese)', value: 'vi', flag: '🇻🇳' },
    { label: 'Bahasa Indonesia', value: 'id', flag: '🇮🇩' },
    { label: 'বাংলা (Bengali)', value: 'bn', flag: '🇧🇩' },
    { label: 'اردو (Urdu)', value: 'ur', flag: '🇵🇰' },
    { label: 'فارسی (Persian)', value: 'fa', flag: '🇮🇷' },
    { label: 'Polski (Polish)', value: 'pl', flag: '🇵🇱' },
    { label: 'Українська (Ukrainian)', value: 'uk', flag: '🇺🇦' },
    { label: 'עברית (Hebrew)', value: 'he', flag: '🇮🇱' },
    { label: 'Dansk (Danish)', value: 'da', flag: '🇩🇰' },
    { label: 'Svenska (Swedish)', value: 'sv', flag: '🇸🇪' },
    { label: 'Norsk (Norwegian)', value: 'no', flag: '🇳🇴' },
    { label: 'Suomi (Finnish)', value: 'fi', flag: '🇫🇮' },
    { label: 'Ελληνικά (Greek)', value: 'el', flag: '🇬🇷' },
    { label: 'Čeština (Czech)', value: 'cs', flag: '🇨🇿' },
    { label: 'Română (Romanian)', value: 'ro', flag: '🇷🇴' },
    { label: 'Magyar (Hungarian)', value: 'hu', flag: '🇭🇺' },
    { label: 'Kiswahili (Swahili)', value: 'sw', flag: '🇰🇪' },
    { label: 'தமிழ் (Tamil)', value: 'ta', flag: '🇮🇳' },
    { label: 'తెలుగు (Telugu)', value: 'te', flag: '🇮🇳' },
    { label: 'Filipino / Tagalog', value: 'fil', flag: '🇵🇭' },
];

export const findCountryDefaults = (countryCode: string): CountryData | undefined => {
    return COUNTRIES_DATA.find((c) => c.code.toUpperCase() === countryCode.toUpperCase());
};
